name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # --- ÉTAPE CRUCIALE POUR RÉSOLRE TON ERREUR OPENGL ---
    - name: Install Graphics Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl-dev \
          libglu1-mesa-dev \
          libx11-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxi-dev \
          libxext-dev \
          libwayland-dev \
          libxkbcommon-dev \
          xvfb

    - name: Configure CMake
      # On pointe bien vers la racine (là où est ton CMakeLists.txt)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # xvfb-run simule un serveur graphique pour que GLFW puisse s'initialiser dans les tests
      run: xvfb-run ctest -C ${{env.BUILD_TYPE}} --output-on-failure